"""Add is_marketing_agreed column

Revision ID: 2332b7bac776
Revises: 7f522ab2f698
Create Date: 2025-11-30 18:47:05.815431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2332b7bac776'
down_revision: Union[str, None] = '7f522ab2f698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_marketing_agreed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_marketing_agreed')
    # ### end Alembic commands ###
