"""add_gender_column

Revision ID: eb7ce1bf9db5
Revises: 2332b7bac776
Create Date: 2025-12-04 13:15:38.007983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb7ce1bf9db5'
down_revision: Union[str, None] = '2332b7bac776'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('gender', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_products_gender'), 'products', ['gender'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_gender'), table_name='products')
    op.drop_column('products', 'gender')
    # ### end Alembic commands ###
